from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class EventType(Enum):
    """Types of events that can be planned."""

    CORPORATE = "corporate"
    PUBLIC = "public"
    PRIVATE = "private"
    HYBRID = "hybrid"


class WorkflowStatus(Enum):
    """Status of workflow execution."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    PAUSED = "paused"


class NodeType(Enum):
    """Types of workflow nodes."""

    SEQUENTIAL = "sequential"
    PARALLEL = "parallel"
    CONDITIONAL = "conditional"
    DECISION = "decision"
    ERROR_HANDLER = "error_handler"


@dataclass
class EventRequest:
    """
    Initial request for event planning.

    This is the input to the workflow system, containing all
    the requirements and constraints for the event.
    """

    event_id: str
    event_type: EventType
    attendee_count: int
    budget: float
    date: str
    location_preference: str
    special_requirements: List[str] = field(default_factory=list)
    dietary_restrictions: List[str] = field(default_factory=list)
    accessibility_needs: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "event_id": self.event_id,
            "event_type": self.event_type.value,
            "attendee_count": self.attendee_count,
            "budget": self.budget,
            "date": self.date,
            "location_preference": self.location_preference,
            "special_requirements": self.special_requirements,
            "dietary_restrictions": self.dietary_restrictions,
            "accessibility_needs": self.accessibility_needs,
        }


@dataclass
class VendorSelection:
    """Details about selected vendors."""

    vendor_type: str  # e.g., "catering", "venue", "entertainment"
    vendor_name: str
    cost: float
    confirmed: bool = False
    backup_vendor: Optional[str] = None


@dataclass
class EventPlan:
    """
    Complete event plan generated by the workflow.

    This is the output of a successful workflow execution,
    containing all the details needed to execute the event.
    """

    event_id: str
    event_type: EventType
    venue: str
    vendors: List[VendorSelection] = field(default_factory=list)
    timeline: List[Dict[str, str]] = field(default_factory=list)
    total_cost: float = 0.0
    risk_assessment: Dict[str, str] = field(default_factory=dict)
    contingency_plans: List[str] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def add_vendor(self, vendor: VendorSelection) -> None:
        """Add a vendor to the plan."""
        self.vendors.append(vendor)
        self.total_cost += vendor.cost

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "event_id": self.event_id,
            "event_type": self.event_type.value,
            "venue": self.venue,
            "vendors": [
                {
                    "vendor_type": v.vendor_type,
                    "vendor_name": v.vendor_name,
                    "cost": v.cost,
                    "confirmed": v.confirmed,
                    "backup_vendor": v.backup_vendor,
                }
                for v in self.vendors
            ],
            "timeline": self.timeline,
            "total_cost": self.total_cost,
            "risk_assessment": self.risk_assessment,
            "contingency_plans": self.contingency_plans,
            "created_at": self.created_at,
        }


@dataclass
class WorkflowNode:
    """
    Represents a single node in a workflow.

    Students will create these when designing workflows.
    The workflow engine will execute them.
    """

    node_id: str
    node_type: NodeType
    name: str
    description: str
    action: Optional[str] = None  # Name of the action to execute
    conditions: Dict[str, Any] = field(default_factory=dict)  # For conditional nodes
    parallel_nodes: List[str] = field(default_factory=list)  # For parallel execution
    next_node_id: Optional[str] = None  # For sequential flow
    error_handler_id: Optional[str] = None  # Node to go to on error

    def __repr__(self) -> str:
        return f"WorkflowNode(id={self.node_id}, type={self.node_type.value}, name={self.name})"


@dataclass
class StateTransition:
    """
    Represents a transition between workflow states.

    This is used for tracking workflow execution and
    understanding the path taken through the workflow.
    """

    from_node_id: str
    to_node_id: str
    condition: Optional[str] = None  # The condition that triggered this transition
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    context: Dict[str, Any] = field(
        default_factory=dict
    )  # Additional data about the transition

    def __repr__(self) -> str:
        cond = f", condition={self.condition}" if self.condition else ""
        return f"StateTransition({self.from_node_id} -> {self.to_node_id}{cond})"


@dataclass
class WorkflowSession:
    """
    Tracks the execution of a workflow instance.

    This is used by the state manager to persist workflow state
    and enable features like pause/resume and checkpointing.
    """

    session_id: str
    event_request: EventRequest
    current_node_id: str
    status: WorkflowStatus
    transitions: List[StateTransition] = field(default_factory=list)
    context: Dict[str, Any] = field(default_factory=dict)  # Workflow execution data
    checkpoints: List[Dict[str, Any]] = field(default_factory=list)  # For recovery
    error_log: List[str] = field(default_factory=list)
    started_at: str = field(default_factory=lambda: datetime.now().isoformat())
    updated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    completed_at: Optional[str] = None

    def add_transition(self, transition: StateTransition) -> None:
        """Record a state transition."""
        self.transitions.append(transition)
        self.current_node_id = transition.to_node_id
        self.updated_at = datetime.now().isoformat()

    def create_checkpoint(self) -> None:
        """Create a checkpoint for recovery."""
        checkpoint = {
            "timestamp": datetime.now().isoformat(),
            "node_id": self.current_node_id,
            "context": self.context.copy(),
        }
        self.checkpoints.append(checkpoint)

    def add_error(self, error: str) -> None:
        """Log an error."""
        self.error_log.append(f"{datetime.now().isoformat()}: {error}")
        self.updated_at = datetime.now().isoformat()

    def complete(self) -> None:
        """Mark the workflow as completed."""
        self.status = WorkflowStatus.COMPLETED
        self.completed_at = datetime.now().isoformat()
        self.updated_at = self.completed_at

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "session_id": self.session_id,
            "event_request": self.event_request.to_dict(),
            "current_node_id": self.current_node_id,
            "status": self.status.value,
            "transitions": [
                {
                    "from_node_id": t.from_node_id,
                    "to_node_id": t.to_node_id,
                    "condition": t.condition,
                    "timestamp": t.timestamp,
                    "context": t.context,
                }
                for t in self.transitions
            ],
            "context": self.context,
            "checkpoints": self.checkpoints,
            "error_log": self.error_log,
            "started_at": self.started_at,
            "updated_at": self.updated_at,
            "completed_at": self.completed_at,
        }


@dataclass
class WorkflowMetrics:
    """
    Metrics for workflow execution performance.
    """

    workflow_name: str
    total_executions: int = 0
    successful_executions: int = 0
    failed_executions: int = 0
    average_execution_time: float = 0.0
    node_execution_counts: Dict[str, int] = field(default_factory=dict)
    error_counts: Dict[str, int] = field(default_factory=dict)

    @property
    def success_rate(self) -> float:
        """Calculate success rate percentage."""
        if self.total_executions == 0:
            return 0.0
        return (self.successful_executions / self.total_executions) * 100

    def record_execution(self, success: bool, execution_time: float) -> None:
        """Record a workflow execution."""
        self.total_executions += 1
        if success:
            self.successful_executions += 1
        else:
            self.failed_executions += 1

        # Update average execution time
        current_total = self.average_execution_time * (self.total_executions - 1)
        self.average_execution_time = (
            current_total + execution_time
        ) / self.total_executions

    def record_node_execution(self, node_id: str) -> None:
        """Record execution of a specific node."""
        self.node_execution_counts[node_id] = (
            self.node_execution_counts.get(node_id, 0) + 1
        )

    def record_error(self, error_type: str) -> None:
        """Record an error occurrence."""
        self.error_counts[error_type] = self.error_counts.get(error_type, 0) + 1

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for reporting."""
        return {
            "workflow_name": self.workflow_name,
            "total_executions": self.total_executions,
            "successful_executions": self.successful_executions,
            "failed_executions": self.failed_executions,
            "success_rate": round(self.success_rate, 2),
            "average_execution_time": round(self.average_execution_time, 2),
            "node_execution_counts": self.node_execution_counts,
            "error_counts": self.error_counts,
        }
